### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ht97a3** [ckiplab/ckip-classic#1]
How can I install this project. Thanks

**Comment by ht97a3** [comment]
When I installing the following message appears:
 warning: I don't know what to do with 'runtime_library_dirs': ['D:\\ckipparser\\lib']
 error: don't know how to set runtime library search path for MSVC

**Comment by emfomy** [comment]
Basically, this tool is only available on Linux. It seems like you're using this project on a Windows system.

I'll try to find out if it is possible to compile this project on Windows systems.
Sorry for the inconvenience.

**Comment by ht97a3** [comment]
Where can I get "ckipparser-linux-root" (i have created it)
I tried to install on Ubuntu, but got the following error:

/usr/lib/python3/dist-packages/pip/commands/install.py:212: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting ckip-classic
  Using cached https://files.pythonhosted.org/packages/14/96/8a24af5221c5db349d4836a72840b36771953e7a96985bac7a57e37ddf1c/ckip-classic-1.0.2.tar.gz
Skipping bdist_wheel for ckip-classic, due to binaries being disabled for it.
Installing collected packages: ckip-classic
  Running setup.py install for ckip-classic ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-j_846ouy/ckip-classic/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rwn4ispc-record/install-record.txt --single-version-externally-managed --compile --parser --parser-dir=/home/ubuntu/ckipparser --user --prefix=:
    running install
    - Disable CKIPWS support
    - Enable CKIPParser support
    - Use CKIPParser library from (/home/ubuntu/ckipparser/lib)
    - Use "Data2" from (/home/ubuntu/ckipparser/Data2)
    - Use "Rule" from (/home/ubuntu/ckipparser/Rule)
    - Use "RDB" from (/home/ubuntu/ckipparser/RDB)
    running build
    running build_py
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/ckip_classic
    copying ckip_classic/ws.py -> build/lib.linux-x86_64-3.6/ckip_classic
    copying ckip_classic/__init__.py -> build/lib.linux-x86_64-3.6/ckip_classic
    copying ckip_classic/parser.py -> build/lib.linux-x86_64-3.6/ckip_classic
    copying ckip_classic/ini.py -> build/lib.linux-x86_64-3.6/ckip_classic
    running build_ext
    building 'ckip_classic._core.parser' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/build
    creating build/temp.linux-x86_64-3.6/build/src
    creating build/temp.linux-x86_64-3.6/build/src/parser
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c build/src/parser/ckipparser.cpp -o build/temp.linux-x86_64-3.6/build/src/parser/ckipparser.o
    creating build/lib.linux-x86_64-3.6/ckip_classic/_core
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/build/src/parser/ckipparser.o -L/home/ubuntu/ckipparser/lib -Wl,--enable-new-dtags,-R/home/ubuntu/ckipparser/lib -lCKIPCoreNLP -lCKIPParser -lCKIPWS -lCKIPSRL -o build/lib.linux-x86_64-3.6/ckip_classic/_core/parser.cpython-36m-x86_64-linux-gnu.so
    /usr/bin/ld: cannot find -lCKIPCoreNLP
    /usr/bin/ld: cannot find -lCKIPParser
    /usr/bin/ld: cannot find -lCKIPWS
    /usr/bin/ld: cannot find -lCKIPSRL
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-g++' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-j_846ouy/ckip-classic/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rwn4ispc-record/install-record.txt --single-version-externally-managed --compile --parser --parser-dir=/home/ubuntu/ckipparser --user --prefix=" failed with error code 1 in /tmp/pip-build-j_846ouy/ckip-classic/

**Comment by emfomy** [comment]
It looks like a linking issue.
Does `libboost_system.so.1.54.0 libboost_thread.so.1.54.0 libCKIPCoreNLP.so libCKIPParser.so libCKIPSRL.so libCKIPWS.so` exists in `/home/ubuntu/ckipparser/lib`?

**Comment by ht97a3** [comment]
I didn't know where to get "ckipparser-linux-root", so I have created it and lib, Data2, Rule , RDB folder and they are empty

**Comment by emfomy** [comment]
The CkipParser is currently available for the commercial license only (https://iptt.sinica.edu.tw/shares/447).
For non-commercial usage, you may try http://parser.iis.sinica.edu.tw/v1/apply.htm.

We are currently developing a new parsing tool that is planned to be released with an academic license.

Sorry for the inconvenience.

**Comment by ht97a3** [comment]
Oh. Thanks you so much

**Comment by ht97a3** [comment]
I could not find a way to use the commercial license.
How can I use the commercial license. Does it work online or offline?

**Comment by emfomy** [comment]
For commercial license, you should contact the Department of Intellectual Property and Technology Transfer (see the email in the post https://iptt.sinica.edu.tw/shares/447) and discuss the price of the tool.

**Comment by ht97a3** [comment]
Thanks for the support!
